### ISSUE TITLE
EC2 Instance Terminated

### ISSUE THREAD

**Issue by CrawfordK** [cat-box/aws-foundry-ssl#3]
After setting up the CloudFormation the EC2 Instance terminated itself?

I'm pointing my domains to Host Gator and one of them is purchased through Whois, would I be able to create a hosted zone on AWS grabbing the domain from Whois?

**Comment by cat-box** [comment]
sounds like the cloudformation stack rolled back. It likely encountered an error with the parameters you provided and deleted the stack, including the ec2 instance. The stack should provide additional information if you click into it.

I'm not familiar with whois and its functionalities but I would imagine no. The only workaround method I know of, is to change your domain's name server from host gator to aws. Otherwise, you can pay a small fee to transfer the domain to aws.

**Comment by CrawfordK** [comment]
> sounds like the cloudformation stack rolled back. It likely encountered an error with the parameters you provided and deleted the stack, including the ec2 instance. The stack should provide additional information if you click into it.
> 
> I'm not familiar with whois and its functionalities but I would imagine no. The only workaround method I know of, is to change your domain's name server from host gator to aws. Otherwise, you can pay a small fee to transfer the domain to aws.

So I want to avoid doing the latter if possible as I currently have a website running on the domain at this time. I will look into DNS options and see what I can figure out. Thanks!
