### ISSUE TITLE
DNS options (please include an option for manual setup/dns)

### ISSUE THREAD

**Issue by bluetardis** [cat-box/aws-foundry-ssl#31]
Love your concept and your work.

Can you please include an option for those of us who have NS and a domain setup.
EG let us manually create/specify an address or output a hostname/address that you have read from AWS.  
Yes I know this will involve using an Elastic IP

I was able to get your solution working but had to muck around with the lets encrypt stuff.

**Comment by zkkng** [comment]
The target audience is non-technical users and its meant to be a very much all-in-one deployment. It would pretty much need to be a totally separate template to do this. 

As you can see we already barely manage to maintain the current deployment, so probably won't take on another. Also the mods on the Foundry discord hate us enough with one template, let alone two.

**Comment by bluetardis** [comment]
> Also the mods on the Foundry discord hate us enough with one template, let alone two.

Thats weird as it was otherwise pretty painless.  
Just had to wrangle with the scripts as I manage my own dns.

**Comment by zkkng** [comment]
If we do add another template down the road, I think it would be a template that utilizes AWS Lightsail. The $5 instance is tempting and it better aligns with the novice scope of the project. Since that would be a rewrite as well, I would look more into making features optional. 

Perhaps a set of nested stacks where the child stacks add specific features such as the DNS so its easier to toggle them on or off.
