### ISSUE TITLE
Mac sftp instructions

### ISSUE THREAD

**Issue by stonematt** [cat-box/aws-foundry-ssl#8]
we could add instructions for this page https://github.com/cat-box/aws-foundry-ssl/wiki/Transferring-Files#mac

along these lines:
https://github.com/stonematt/aws-foundry-ssl/wiki

**Comment by cat-box** [comment]
I've intentionally chosen to leave out cli sftp instructions since this is intended to be a fool proof, beginner friendly guide. I personally don't think cli usage is as fool proof as most users are much more comfortable with an UI. Cyberduck covers sftp for mac users and is fairly simple to use once set up.

This is also a preventative measure to discourage the use of SSH unless the user is familiar with linux commands. I've mainly done this to minimize the chance of accidental deletes. If the maintainer of the server is comfortable enough to ssh in and modify their config file, I trust they also already know how to use sftp via cli.

However, if the demand for CLI sftp instructions increases, I can definitely add it in.
